# get http://localhost:8080/videos


# get http://localhost:8080/videos/84e96018-4022-434e-80bf-000ce4cd12b8

POST http://localhost:8080/videos HTTP/1.1
content-type: application/json

{ 
    "title": "title",
    "description": "description"
}